name: Deployment
on:
  push:
    branches:
      - 'dev'
      - 'int'
      - 'prod'
    paths:
     - 'Development/**'
     - 'Integration/**'
     - 'Production/**'
jobs:
  dev-deployment:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: Development
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: authenticate with gcp
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'
      - name: set up gcloud
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: moving files to bucket
        run: |
          gcloud storage rsync -r . gs://dev-bucket-12341/