name: Deployment
on:
  push:
    branches:
      - 'dev'
jobs:
  dev-deployment:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      release_tag: ${{ steps.fetch.outputs.upcoming_version }}
    steps:
      - name: fetching tag
        id: fetch
        run: |
          version=$(grep -Po '\#\# \d.\d.\d.\d+ - \d\d\d\d-\d\d-\d\d' RELEASE_NOTES.md | grep -Po '(\d+\.\d+\.\d+\.\d+)' | head -1)
          echo "version:$version"
          echo "upcoming_version=$version" > $GITHUB_OUTPUT
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: authenticate with gcp
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'
      - name: set up gcloud
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: moving files to bucket
        run: |
          gcloud storage rsync -r . gs://dev-bucket-12341/
  tag-release:
    runs-on: ubuntu-latest
    needs: dev-deployment
    steps:
      - name: create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.dev-deployment.outputs.release_tag }}
          release_name: release-${{ needs.dev-deployment.outputs.release_tag }}
          body: |
            release-${{ needs.dev-deployment.outputs.release_tag }}
