name: Deployment
on:
  push:
    branches:
      - 'dev'
jobs:
  dev-deployment:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      release_tag: ${{ steps.fetch.outputs.upcoming_version }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: fetching tag
        id: fetch
        run: |
          version=$(grep -Po '\#\# \d.\d.\d.\d+ - \d\d\d\d-\d\d-\d\d' RELEASE_NOTES.md | grep -Po '(\d+\.\d+\.\d+\.\d+)' | head -1)
          echo "version:$version"
          echo "upcoming_version=$version" > $GITHUB_OUTPUT
      - uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with: 
          tag: ${{ steps.fetch.outputs.upcoming_version }}
      # - run: echo "Tag ${{ steps.fetch.outputs.upcoming_version }} already exists!. Please check and update proper version"
      #   if: steps.check-tag.outputs.exists == 'true' 
      - name: result of checking tag in previous step
        run: |
          if [ ${{ steps.check-tag.outputs.exists }} == 'true' ]; then
            echo ""Tag ${{ steps.fetch.outputs.upcoming_version }} already exists!. Please check and update proper version""
            exit 1
          fi
      # - name: authenticate with gcp
      #   uses: 'google-github-actions/auth@v2'
      #   with:
      #     credentials_json: '${{ secrets.GCP_CREDS }}'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/bustling-joy-417204/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions'
          service_account: 'github-actions-sa@bustling-joy-417204.iam.gserviceaccount.com'
      - name: set up gcloud
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: moving files to bucket
        run: |
          gcloud storage rsync -r . gs://dev-bucket-12341/
  tag-release:
    runs-on: ubuntu-latest
    needs: dev-deployment
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: release-${{ needs.dev-deployment.outputs.release_tag }}
          tag_name: ${{ needs.dev-deployment.outputs.release_tag }}
          body: |
            release-${{ needs.dev-deployment.outputs.release_tag }}
